apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription
  namespace: knative-eventing
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    name: channel-defaults
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: custom-http-target
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: custom-http-target